<?php
$files_download='download';
$files_upload='files\\upload';
$files_tmp='files\\tmp';
$files_log='files\\log'; 
$files_db='files\\db';
$files_exe='files\\exe';
$files_journal='files\\journal';
$files_store='files\\store';
$files_units='files\\units';
?>
