unit TestcgsCHPR;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, publ, cgsCHPR, Dialogs, Classes, Windows;
type
  // Test methods for class TChprList
  
  TestTChprList = class(TTestCase)
  strict private
    FChprList: TChprList;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestClear;
    procedure TestAutoConfig;
    procedure TestDoEnum;
    procedure TestHideAll;
    procedure TestPodstava;
    procedure TestShowAll;
    procedure Test;
  end;

implementation

procedure TestTChprList.SetUp;
begin
  FChprList := TChprList.Create;
end;

procedure TestTChprList.TearDown;
begin
  FChprList.Free;
  FChprList := nil;
end;

procedure TestTChprList.TestClear;
begin
//  FChprList.Clear;
  Check(true);
end;

procedure TestTChprList.Test;
var
  Result:boolean;
  sts: TStringList;
begin
  sts := TStringList.Create;
  FChprList.Text:='A,B,C,D'
  +#13#10+'1,2,3,4'
  +#13#10+'5,1,2,16'
  +#13#10+'6,4,1,15'
  +#13#10+'7,3,4,14'
  +#13#10+'8,2,3,13'
  +#13#10+'9,1,2,12'
  +#13#10+'10,4,1,11';
  FChprList.SortedField:=3;
  FChprList.Filter:='12';
  Result:=FChprList.AsTable.Text=''
  +'A|B|C|D '+#13#10
  +'-|-|-|--'+#13#10
  +'9|1|2|12'+#13#10;
  Check(Result);
  sts.Free;
end;

procedure TestTChprList.TestAutoConfig;
begin
//  FChprList.AutoConfig;
  Check(true);
end;

procedure TestTChprList.TestDoEnum;
begin
//  FChprList.DoEnum;
  Check(true);
end;

procedure TestTChprList.TestHideAll;
begin
//  FChprList.HideAll;
  Check(true);
end;

procedure TestTChprList.TestPodstava;
begin
  // TODO: Setup method call parameters
  Check(true);
  // TODO: Validate method results
end;

procedure TestTChprList.TestShowAll;
begin
  Check(true);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTChprList.Suite);
end.

